force-app/main/default/objects/TV_Show__c/TV_Show__c.object-meta.xml
<CustomObject>
    <label>TV Show</label>
    <nameField>
        <label>TV Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Show__c/fields/Img__c.field-meta.xml
<CustomField>
    <fullName>Img__c</fullName>
    <label>Img</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TVShowController.cls
/**
 * @author Dominika Szuba <dominika.szuba@accenture.com>
 * @date 03/04/2024
 * @description This class provides methods for TV_Show__c object.
 */
public with sharing class TVShowController {
    /**
     * @author Dominika Szuba <dominika.szuba@accenture.com>
     * @date 03/04/2024
     * @description The method returns list of TV_Show__c with their Id, Name, Img__c.
     */
      @AuraEnabled(cacheable=true)
      public static List<TV_Show__C> getTVShows() {
          return [SELECT Id, Name, Img__c
                  FROM TV_Show__C
                  ORDER BY Name];
      }
  }