force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/TV_Show__c.field-meta.xml
<CustomField>
    <fullName>TV_Show__c</fullName>
    <label>TV Show</label>
    <referenceTo>TV_Show__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Show__c/TV_Show__c.object-meta.xml
<CustomObject>
    <label>TV Show</label>
    <nameField>
        <label>TV Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SendEmailAfterNewSeasonTest.cls
@isTest
private class SendEmailAfterNewSeasonTest {
  /**
   * @author Dominika Szuba <dominika.szuba@accenture.com>
   * @date 08/04/2024
   * @description This method verifies number of future calls.
   */
    @isTest
    private static void testSendEmail(){
        TV_Show__c testShow = new TV_Show__c();
        testShow.Name = 'Test Show';
        testShow.Description__c = 'Test description';
        insert testShow;
        
        List<Season__c> seasons = new List<Season__c>();
    	for(Integer i = 0; i < 5; i ++) {
        	Season__c season = new Season__c();
            season.Name = 'Test Season' + i;
            season.TV_Show__c = testShow.Id;
            seasons.add(season);
    	}
        insert seasons;

        List<Id> insertedIds = new List<Id>();
        for(Season__c season : seasons) {
            insertedIds.add(season.Id);
        }   

        Test.startTest();
        SendEmailAfterNewSeasonTriggerHandler.sendMail(insertedIds);
        Integer invocations = Limits.getFutureCalls();
        System.assertEquals(1, invocations, 'One email should be sent.');
        Test.stopTest();
    }
}