force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/TV_Show__c.field-meta.xml
<CustomField>
    <fullName>TV_Show__c</fullName>
    <label>TV Show</label>
    <referenceTo>TV_Show__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Show__c/TV_Show__c.object-meta.xml
<CustomObject>
    <label>TV Show</label>
    <nameField>
        <label>TV Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TVShowDetailController.cls
public with sharing class TVShowDetailController {
    @AuraEnabled(cacheable=true)
    public static List<Season__c> getSeasonsByTvShowId(String tvShowId) {
        return [SELECT Id, Name
                FROM Season__c
                WHERE TV_Show__c = :tvShowId 
                ORDER BY Name];
    }

    @AuraEnabled
    public static List<Episode__c> getEpisodesBySeasonId(String selectedSeasonId) {
        return [SELECT Id, Name, Season__c
                FROM Episode__c
                WHERE Season__c = :selectedSeasonId 
                ORDER BY Name];
    }

    @AuraEnabled
    public static List<User> getUserById(String userId) {
        return [SELECT Id, Name, UserRoleId
                FROM User
                WHERE Id = :userId 
                LIMIT 1];
    }
}