force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Episodes</relationshipLabel>
    <relationshipName>Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/TV_Show__c.field-meta.xml
<CustomField>
    <fullName>TV_Show__c</fullName>
    <label>TV Show</label>
    <referenceTo>TV_Show__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Show__c/TV_Show__c.object-meta.xml
<CustomObject>
    <label>TV Show</label>
    <nameField>
        <label>TV Show Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Shows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EpisodeControllerTest.cls
@isTest
public with sharing class EpisodeControllerTest {
  /**
   * @author Dominika Szuba <dominika.szuba@accenture.com>
   * @date 08/04/2024
   * @description The method sets up data for tests.
   */
    @testSetup
    static void setup() {
        TV_Show__c testShow = new TV_Show__c(Name = 'Test', Description__c = 'Description Test');
        insert testShow;

        Season__c testSeason = new Season__c(Name = 'Test', TV_Show__c = testShow.Id);
        insert testSeason;

        Episode__c testEpisode = new Episode__c(Name = 'Test Season', Season__c = testSeason.Id, Description__c = 'Test description');   
        insert testEpisode;
    }

  /**
   * @author Dominika Szuba <dominika.szuba@accenture.com>
   * @date 08/04/2024
   * @description The method verifies if all episodes are returned alphabetically.
   */
    @isTest
    static void shouldReturnAllEpisodes() {
        Episode__c episode = [SELECT Id, Name FROM Episode__c LIMIT 1];

        Test.startTest();
        List<Episode__c> returnedEpisodes = EpisodeController.getEpisodesById(episode.Id);
        Test.stopTest();
        
        System.assertEquals(1, returnedEpisodes.size(), 'Number of returned episodes is incorrect.');
    }
}